
global:
  postgresqlEnabled: true
  valkeyEnabled: true
  redisEnabled: false

penpot:
  persistence:
    assets: 
      enabled: true
  ingress:
    enabled: true
    hosts:
      - penpot.mw.local
    tls:
      - secretName: penpot-cert
        hosts:
          - penpot.mw.local
    