
global:
  postgresqlEnabled: true
  valkeyEnabled: true
  persistence.assets.enabled: true
  redisEnabled: false

penpot:

  ingress:
    enabled: true
    hosts:
      - penpot.mw.local
  tls:
    - secretName: penpot-cert
      hosts:
        - penpot.mw.local
    