apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
  namespace: catcode
data:
  etcd.conf.yml: |
    name: etcd-0
    data-dir: /var/lib/etcd
    initial-advertise-peer-urls: http://etcd-0.etcd:2380
    advertise-client-urls: http://etcd-0.etcd:2379
    listen-peer-urls: http://0.0.0.0:2380
    listen-client-urls: http://0.0.0.0:2379
    initial-cluster: etcd-0=http://etcd-0.etcd:2380
    initial-cluster-state: new
