apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: catcode
  annotations: {
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  }
spec:
  ports:
    - port: 80
      targetPort: 2379
  selector:
    app: etcd
