apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-cert
  namespace: monitoring
spec:
  secretName: loki-tls-secret
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - loki.mw.local
  duration: 8760h
  renewBefore: 720h
