apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: penpot-cert
  namespace: penpot
spec:
  secretName: penpot-tls-secret
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - penpot.mw.local
  duration: 8760h
  renewBefore: 720h
