apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vaultwarden.mw.local
