apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: argo-image-updater
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
  applicationRefs:
    - namePattern: "webhook-forwarder"
      images:
        - alias: webhook-forwarder
          imageName: docker-registry.mw.local/mwstack-webhookforwarder
          manifestTargets:
            helm:
              name: "deployment.image.repository"
              tag: "deployment.image.tag"
      writeBackConfig:
        method: git
        gitConfig:
          branch: master
          writeBackTarget: helmvalues:values.yaml
    - namePattern: fittracker-backend
      images:
        - alias: fittracker-backend
          imageName: docker-registry.mw.local/fittracker-backend
          manifestTargets:
            helm:
              name: "deployment.image.repository"
              tag: "deployment.image.tag"
      writeBackConfig:
        method: git
        gitConfig:
          branch: master
          writeBackTarget: helmvalues:values.yaml