apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: argo-image-updater
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "webhook-forwarder"
      images:
        - alias: "webhook-forwarder"
          imageName: docker-registry.mw.local/mwstack-webhookforwarder
          manifestTargets:
            helm:
              name: "deployment.image.repository"
              tag: "deployment.image.tag"
  writeBackConfig:
    method: "git"
    gitConfig:
      branch: "main"
      writeBackTarget: "helmvalues:./values.yaml"
