apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Docker Registry MW Local
      prefix: docker-registry.mw.local
      api_url: https://docker-registry.mw.local
      default: true
      insecure: true