apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - argocd.mw.local
  duration: 8760h
  renewBefore: 720h
