apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pulsar-manager
  namespace: pulsar
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`pulsar-manager.mw.local`)
    priority: 10
    services:
    - name: pulsar-manager
      port: 80

