apiVersion: v1
kind: PersistentVolume
metadata:
  name: pulsar-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/ext1/pulsar/data
    server: 192.168.0.11
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pulsar-data-pvc
    namespace: pulsar
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pulsar-conf-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/ext1/pulsar/conf
    server: 192.168.0.11
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pulsar-conf-pvc
    namespace: pulsar
