apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulsar-data-pvc
  namespace: pulsar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulsar-conf-pvc
  namespace: pulsar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi