apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:
      k8sattributes:
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
          labels:
            - tag_name: app.label.component
              key: app.kubernetes/component
              from: pod
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: connection
      transform:
        log_statements:
          - context: log
            statements:
              - set(attributes.level) = attributes.severity
              - set(attributes.msg) = attributes.body
              - set(attributes.filepath) = attributes['attributes.code.filepath']
              - set(attributes.function) = attributes['attributes.code.function']
              - set(attributes.lineno) = attributes['attributes.code.lineno']
              - set(attributes.deployment) = attributes['resources.k8s.deployment.name']
              - set(attributes.namespace) = attributes['resources.k8s.namespace.name']
              - set(attributes.node) = attributes['resources.k8s.node.name']
              - set(attributes.pod_name) = attributes['resources.k8s.pod.name']
              - set(attributes.pod_ip) = attributes['resources.k8s.pod.ip']
              - set(attributes.service_name) = attributes['resources.service.name']
              - set(attributes.service_namespace) = attributes['resources.service.namespace']
    exporters:
      loki:
        endpoint: "http://loki-service.monitoring.svc.cluster.local:80/loki/api/v1/push"

      otlp:
        endpoint: "tempo-service.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors:
            - k8sattributes
            - batch
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors:
            - k8sattributes
            - batch
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors:
            - k8sattributes
            - transform
            - batch
          exporters: [loki]
