---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB4+zGL1f1oF8jJravFpE8qpE75Yo4hGGSjhXrOFWKDs0ADENDtCFmRVuYgEtmUgOeRH/SkubiQNw7pcxPioxtUkKXbhYKY1BOBOB9OkoZWvoolFOPvpN9ZNcZiDtnVYeKK8zl4rw3/JyGnV+cY/+C+UVxBYPvGf6H+Kzu5px07nzwoUg+qzfsw++g7aEWiWkmEWqaX7yev1w+DCuwyqQPVO7ytZKRt560NGKqUoxJEoeuDbFbj9rUrQ7n79xp+Q6VNQoRfxg25HxZkliXNdNGxE8PutE6XPUwVERf+wFkQ3mWPJfbN6+mbS6DAlDLoF2Zkdu4TOddYsLwVwKXEfVWuL01/RUnE9Olcvx1FvxH7LJ8EfjxW6JPWMpfOqwjwb2l17wMYBXqWFzeWMrnuFT0Q+TKWXBGMpwqzgNCzr0di8LhzfHAKOeE1jd4jBgBKYBuH+FveHFREpNteZ8dx9MI+Md6jqLKq0qaVl+v3F8fzVKH+pzlktzPeBgikKizG3eibbX/DWG/AX//zw2wVm15YotKoyMGGr66+xSWpRwZTyXcUIt/Eo5+gU13R/CfGN7lam+f+jNVnHoB9ty3Ao2ynCetncaoIGL1zJj5kqwxD7JzZ2KUnaG9CN92ad8qVI0UEUbE9mzGJdOGGLbIQRnfTgJ3flaBBD6TgaDC7m/D+d8EIhcwrATCgidnR11ceZ5NQqILfW8i/J+E4EQtiWtmVfH2K9ezHz7pkV1IYCY9oHkulFV3RQIx1Cqcl2Zx9nEq76Ps3FB4zNA9TwhZa5NIdObjnjarl+YMgbGjfVRbuK7w66tkAwv5lIdm5znaYuGoNTCRHEiCMm4JvD/9oMqonswP0EZPYWCY/cGxqiHEX1cxxitrPsyfz9rrm/vIXSKTGOeEHI2ol0324Q+BdfMTzTuqnhosEPuC8/h8JLjuUBYuOUsIylhCj
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
