---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAjG34QlyZipEQ252H8SKSsEJGXXmyLs5AiV7plW1MRrjiLbGrovrBWvlnXUFhj3wCyLjEVRkJWM1eN9ofuchKNeo9mhdejDyczNbBSj3V9nxSloEHxxohLDzKLTcwbx8OFoEfrHMq9vwUUv5GpBvSNl+7y7KnTffa21Ke+q6djQKnIsPP/dNWgA8u3uSQd9n31o/sZq+5KvBtcRJbTXQNllT0IdM0JrZqhNWHgA1zsou2pxJR0DcSK4Kyarp4zaTv6xKolkq3IpLvxXDJJPlx57j2dqR5suGlcCadUiOQ8d+axh1kwE1/xjeOuo0An0XSJmi959bwdHmAXXTv23daUpXsCSP/HY7/wC1vI5vsKPxNe3jRKq3vD16P29A2czcA2vn6qTj9GfPF6XIWV7C5DzHQUALMS6w93kZsMVLbvrUpfbQ3afKfKY2U1omghYSpBK96V4Fqrt9EGhWlnxVRLAcTSM4jZBaAWGOAzMTX7IPaVNqAr4j/JJUIgpVu+S771lKsMl/9uxODD5S1TmeGWaHUCduOCv9BVYKSHpIHJKb6g/LzG5TwfMyVgqFxvLQhM0yJ+1I5/BT4Oux/Z5cyXuwcVYx0z+li6lyA10FRON0PlNKjwgdUHorUNTH4qBgUj/qmGcf1A1iKlEWi6POygIhk766mcfbU8cdoa5iRAA0IiULHB+rtFgAjnmubz/D20IvTOHBKQDhONRrsFFmk+mbuutgoMo+Jzmv4SxlWpqjpxy5HNjmqW9p5vneOgDnOKWwKr+e+HHCO3IbxtDrFF2tZcOHy6GdUJmtg3xB84OJEDq4sDlVq4me+We3vxXop3+HIwR/qUAzXWznRhSAFNNADP1yVwsr+ne0BChG5DWmodVjOvHExCmh3c8H70mpLTtriBUjyIHYkJ4jlZtZCXoa+e4+4U3LuGYRe9x7q7kYWJ8yaD3QY8
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
