---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCQzNNl1pERqBjDL2cW1FuPCAdfI0xCosKTSIAIu8T4ti+4wFfg1Fp721YHfHhqU+n07wZz3lDNIvAayBRE+EpSvILUdrodV6JtFtin+L1JyOajDaxZZrFBW4Yyf+gcwAdbJEf+PdWDrmfYFvKqO7NkNhHRNyUJ+GcyBY9D4xDTLW0K1N6wHBoypAjjUDGDrtkrEuBmpjldN+YBilzMoIi1hMBFibaf93C+NvMzzI1YypF+qPl63Qr+jnOHmJhg521wUPvRJ6jS7aUjbHFXC6+rANuVfFbqqP2+pN+TVuRqFfndbUk+NZpE3oRaVFPPkBXYV/06HkQ9uXr3ox2hhpEJw81opr/+8xqOs/Uz+oL9Lar+tTI4Knh7S96E4aNhelCS0OT718IqPesgHECB7HqA9aG2xJ21w6s3OaGUgZbv9EG+oRfPUD2NIWPoGF8cunQ48XLLGw4PO2sdJvHdEeZmbSY8EpjqKh435LeSp8sxmZOJY/qvOmgYtvilnRhHut+ojg/ZQIm8wGn0fprbyE0FmINIsUdn86eHRBaoDG7QMdx7X1jKG+l49Cxk2RuxcVVzQZL7ZwLmODKpXRDYTms5AwVOIqg4a+7kKMuBohUWHOMJB5TpO6MnLf3DUWrQ91pG41j7Kh6l+4aLTGQVEYNRYVCa3g+YhJFg+T0wyj7IoRv7lhtY4q7fQrVFiW41iV2WfSZedtK1KG9Do8dPZKgCFh5Y9OyK9ixb+47BIaBakJbmW6juWMBGv+h7jYYHIruQ44I9n48UVPleNYlFVIK/nKenaLYp5XzeFgxXyivGDmhfaWPOkcK+p2MlzNetZHckqK162bK74gPOa8tCOGs4SD7/gb2vtxutYnj0po4Eu0eUWiDaYzF31baPXK2H6YMUxNJn
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
    type: Opaque
