---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDGqkdP7qnXwSJcYMCePr4aDw/6xzONu/hFmg0+AClxaoFoR9kBgsMQqv6sg1LWs8VX6dpKtSRyFGNcEAbF7gzZaavPug0if0CpdK67NhREK4B9P0Cg29I2rdmOGoEXesRdEfjulS00VAxajAMqCn3151VpvXkQeX4d6Wzm+erAmrnl9hwu8R/HWehlTlek1zcd5liBol9CPTcbCcosJcqM7uuy9BokaYF5r9ehqwBeLWMZ/q4PRNKJFDaGOgbWT8JRKHb15k2tNfgCQ3JcB1JO8A6wamgCuG6AzoxoMhO56MSev+g8YWGdif92ZBivTqjnNkygj0zOuY8a5Aft9Qw+FcUB2/lb1Yw/r2LsCfkgRPJXpHhRfvPC5abeHj300V1yF2V3ZVB6WGGpbj5um8Ija53hobeGx+O1aSlvEgAVjum5JHi/VijXtshFkd+gGQLrNhsiUU5577rNkChlP9YhcDA4g+WcVebF3kc5smGXv9QHQmacfsVHmhNr/lnCFekjA7ViJeXaoo606JXtBs4l88a53eq5O9ClQNwt7EgpOGf3UtYRxFnv0oxaJUX8zG6IDs/SXYC6V5I1tmN+yMzoKMDR4PTs46SSKovTanB7oGgt/t+y1PV/pVeGORVbsViL4ku99TtZ3qJ0C8xxl45Mk2Uc4yJVa5DwmkJmgoV+QTu4KK8WIdY/rql0BDNfgEzo6aTFoP7lFZnQWQhibaL4vts3yxBy62yD/DVp/XQhWvYzgYE=
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
