---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB3xwnL2GxV54pJ8ijSpPpiYEy+9c3aruUN5PqMTj/vgCtuPemYc7pwEvkUUtdA34Ka1Aqm5HfraKheTiOXHbLP9+ZMmspad91Cs7DjfCeoL28F6lZcP22lFakkL2tzsEbLlWLn56nK5pbvU/Ak0vUBJQxvLe9J6KBGTXQychGbt5PSKA4UReoimW8QzjDd4o+Kb1TQHAIGDuZvNmb6zjlnSa113LGkkTxwnJuZk9opbE4bIsG7tkmXMYgirZ/mtPuh4pvORHBQJpXG4kn7sgWH1UYIi3clkblReL/SCVTBiblwuwxmjL+rMxvd7A2a6FhCQIJii6TzV++E9O2EkrrO/zyOdK2eRzJVo1OVlwwKzoyCC6WoqhX9oHntv3iJ59XZARnCoklj88tXnZbNLBSWiTFsNqo0SoJFSkw0A1UNOnMYRgNonNhlane11s/97iQ4ofobTqga6JZhVQvbts5Ai1VuQ+pYvaa8K8ff8O37gwSzZ0SnNH3rsgKLezdwhL1E3vjX9ZAxyHCKJlSrCcRn625pTsHfTlgKZDqsA+jizka1DyRLmoLmWVKgzk/cZ+/+7CsWNFSj4iEvfjmcsKeqRd7O8Vv3JS7dpNcP/e6i1U8g62p6nskT4K+0d6GISL99DAenuYFHyOXHpAu9oHXg83PJPPBTGqqxB+iLmVO5HJG69jK3GPKosp6PfkXDzKeUbSxrP5PhHwTTkpo3NGtqlu0Li4QeopbKi/8rr0XYVoe/zdAHQ5orh/8PJ0IGK0UQCjLnqmcMHbIHBCE6sL5bpzvOv2kWJn2fYgKcNsfCPstb05CJPg1oB6w2OHcPKCGafMjwWiUzNsDobvRANAVagSJf2ic0ToNZc2zmdFu+7CoTH3/n5l5fl1Df/oBVA5BhWBT4
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
    type: Opaque
