---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBvTRCoioNt0OTUj+7v+8qg3eUoSun2f/JHqkBUjBeiHmy/CgjJLcTbhyLeAL0rUM5i5cNpD8mRJHnkndPSNk3m8IiahZ4BiBXEuJk0DX9VI4tpZnMpE+cI+3aMI3CI+0AHTiGDowqW+2+9ER6bCcdOLAe56p38ZBTEBJYbIK3FYzfWTQH2spGLKbY9dHos7lsRC4VXJAzcgL8MMc/chOLf2c6x8y7TjFmOJwngd2KtgB6Pv3pWZ8UHrS1dzy1tq28retucDnsH03fxV1Y28omHsRQJWDZaFc24bkh4XiZfBmG6TVjifc8M7aPPKyvby/4I0KYyme0yYEqz0ThGykAZugN8oUgIuqBu10THDlOszTpRF+PWAki2gcJU5xcOBT+BB1TDM441bR1QcEQX27yj4TGrOEKzYeTGwYyO6OfIemNeIiokNq7P6xMQXl21gasn9G13ELDnqI0lOAsCaSfu7L+OL3ZWMmNTEman6bRW75IuD8iukKRPZWQdjhoK7vbKAa5a8A7RddCAUP8B6Fifua7rWzlDUhgFjATwjdcaEYvYG8UYcaI104vegQs+6JieGMDwde4oK+rRb+ULoIUs5cpcy/BDVAJam5ZO+YemooWqyAGC2lyHW5KrWorI4zTaIK+5tNfwFuH4KBJvADQOLsDLqBJaMxHudp85MKtShpG4P77hrpVd/VilUOrL8GnO0eAmCZATcsIEI9k7f1LfHhDwowAayw+Cb0ztfq1l1Dbr6M4=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
    type: Opaque
