apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: build-pipeline
spec:
  template:
    serviceAccountName: argo-events-build-pipeline-sa
  dependencies:
    - name: webhook-dep
      eventSourceName: build-pipeline-webhook
      eventName: build-pipeline
  triggers:
    - template:
        name: build-pipeline-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: build-pipeline-workflow-
              spec:
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["hello world"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-build-pipeline-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-build-pipeline-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-build-pipeline-rolebinding
subjects:
  - kind: ServiceAccount
    name: argo-events-build-pipeline-sa
roleRef:
  kind: Role
  name: argo-events-build-pipeline-role
  apiGroup: rbac.authorization.k8s.io