apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: build-pipeline-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
    metadata:
      labels:
        app: event-source-webhook
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    build-pipeline:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /build
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST