# https://github.com/bakito/sealed-secrets-web

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealedsecrets-ui
  namespace: sealedsecrets
  labels:
    app: sealedsecrets-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealedsecrets-ui
  template:
    metadata:
      labels:
        app: sealedsecrets-ui
    spec:
      serviceAccountName: sealedsecrets-ui
      containers:
        - name: sealedsecrets-ui
          image: ghcr.io/bakito/sealed-secrets-web:main # https://github.com/bakito/sealed-secrets-web/pkgs/container/sealed-secrets-web
          args:
            - --sealed-secrets-service-namespace=sealedsecrets
            - --sealed-secrets-service-name=sealed-secrets-controller
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
          env:
            - name: SEALED_SECRETS_CONTROLLER_NAMESPACE
              value: sealedsecrets
            - name: SEALED_SECRETS_CONTROLLER_NAME
              value: sealed-secrets-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealedsecrets-ui
  namespace: sealedsecrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sealedsecrets
  name: sealedsecrets-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "services/proxy"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealedsecrets-ui-rolebinding
  namespace: sealedsecrets
subjects:
  - kind: ServiceAccount
    name: sealedsecrets-ui
    namespace: sealedsecrets
roleRef:
  kind: Role
  name:  sealedsecrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: sealedsecrets-ui-svc
  namespace: sealedsecrets
spec:
  selector:
    app: sealedsecrets-ui
  ports:
    - port: 80
      targetPort: 80
    
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sealed-secrets-web-ingress
  namespace: sealedsecrets
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`sealedsecrets.mw.local`)
    priority: 10
    services:
    - name: sealedsecrets-ui-svc
      port: 80

