apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@*/*':
        access: $all      # Allow all users to access scoped packages
        publish: $all     # Allow all users to publish scoped packages
      '**':
        access: $all      # Allow all users to access all packages
        publish: $all     # Allow all users to publish all packages
    logs:
      - { type: stdout, format: pretty, level: http }

    # Disable web UI login/signup button (optional)
    security:
      web:
        sign: false
