apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/

    # Allow anonymous access and publishing for all packages
    packages:
      '@*/*':
        access: $all      # Allow anonymous access to scoped packages
        publish: $anonymous     # Allow anonymous publishing to scoped packages
        unpublish: $anonymous   # Allow anonymous unpublishing
      '**':
        access: $all      # Allow anonymous access to all packages
        publish: $anonymous     # Allow anonymous publishing to all packages
        unpublish: $anonymous   # Allow anonymous unpublishing

    logs:
      - { type: stdout, format: pretty, level: http }

    # Disable authentication entirely
    auth: {}

    # Disable web UI login/signup button
    security:
      web:
        sign: false
