apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage
    auth:

    # a list of other known repositories we can talk to
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/

    packages:
      '@*/*':
        # scoped packages
        access: $all
        publish: $all
        proxy: npmjs

      '**':
        access: $all
        publish: $all
        proxy: npmjs

    logs:
      - { type: stdout, format: pretty, level: http }