apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage
    web:
      title: Verdaccio


    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    # a list of other known repositories we can talk to

    packages:
      '@*/*':
        # scoped packages
        access: $all
        publish: $all
        unpublish: $all
        proxy: npmjs

      '**':
        access: $all
        publish: $all
        unpublish: $all
        proxy: npmjs
    server:
      keepAliveTimeout: 60

    logs:
      - { type: stdout, format: pretty, level: http }