apiVersion: v1
kind: PersistentVolume
metadata:
  name: verdaccio-pv
  namespace: verdaccio
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/ext1/verdaccio
    server: 192.168.0.11

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-pvc
  namespace: verdaccio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage

