# Steps
# 1. Git clone
# 2. Build docker image
# 3. Push to registry
# 4. Update image version in helm
# 5. Push update to git

# Use generic-image-builder

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-pipline
spec:
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 1m
  entrypoint: build-and-deploy
  serviceAccountName: argo-workflow-svc
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  arguments:
    parameters:
      - name: giturl
        value: git@github.com:MatiWall/  # Provide the correct GitHub URL here
      - name: revision
        value: HEAD
      - name: branch
        value: master
      - name: repo
        value: catcode-backend
      - name: subpath
        value: services/core-api
      - name: registry
        value: docker-registry.mw.local/
      - name: base-image
        value: python:3.12-3
      - name: git-application-values
        value: git@github.com:MatiWall/homelab.application-values.git
      - name: username
        value: matiwall
      - name: email
        value: matiwall@live.dk
  templates:
    - name: build-and-deploy
      dag:
        tasks:
          - name: git-clone
            templateRef:
              name: git-template
              template: git-clone
            arguments:
              parameters:
                - name: url
                  value:  "{{workflow.parameters.giturl}}{{workflow.parameters.repo}}"
          - name: build
            dependencies: [git-clone]
            template: build
            arguments:
              parameters:
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
          - name: update-version
            dependencies: [git-clone]
            template: update-version
            arguments:
              parameters:
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"
          - name: extract-name-and-version
            dependencies: [update-version]
            template: extract-name-and-version
            arguments:
              parameters:
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
          - name: tag-and-push
            dependencies: [extract-name-and-version, build]
            template: tag-and-push
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: application-name
                  value: "{{tasks.extract-name-and-version.outputs.parameters.application-name}}"
                - name: version
                  value: "{{tasks.extract-name-and-version.outputs.parameters.version}}"
          - name: git-push
            dependencies: [tag-and-push]
            templateRef:
              name: git-template
              template: git-push
            arguments:
              parameters:
                - name: username
                  value: "{{workflow.parameters.username}}"
                - name: email
                  value: "{{workflow.parameters.email}}"
                - name: path
                  value: "{{workflow.parameters.repo}}"
                - name: commit-message
                  value: "Updated {{tasks.extract-name-and-version.outputs.parameters.application-name}} to {{tasks.extract-name-and-version.outputs.parameters.version}}"
                  
          - name: update-values
            dependencies: [tag-and-push]
            templateRef:
              name: application-values-tag-updater
              template: update-values-tag
            arguments:
              parameters:
                - name: version
                  value: "{{tasks.extract-name-and-version.outputs.parameters.version}}"
                - name: application-name
                  value: "{{tasks.extract-name-and-version.outputs.parameters.application-name}}"
