apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generic-image-builder
spec:
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 1m
  entrypoint: build-and-deploy
  serviceAccountName: argo-workflow-svc
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  arguments:
    parameters:
      - name: giturl
        value: git@github.com:MatiWall/ 
      - name: repo
        value: FitTracker
      - name: subpath
        value: 
      - name: registry
        value: docker-registry.mw.local/ #docker-registry-service.docker-registry.svc.cluster.local:5000
      - name: application-name
        value: fittracker-backend
  templates:
    - name: build-and-deploy
      dag:
        tasks:
          - name: git-clone
            templateRef:
              name: git-template
              template: git-clone
            arguments:
              parameters:
                - name: url
                  value:  "{{workflow.parameters.giturl}}{{workflow.parameters.repo}}"
          - name: generate-tag
            dependencies: [git-clone]
            template: generate-tag
            
          - name: build
            templateRef:
              name: docker-templates
              template: build
            dependencies: [git-clone]
            arguments:
              parameters:
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
          - name: push
            templateRef:
              name: docker-templates
              template: tag-and-push
            dependencies: [build, generate-tag]
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: subpath
                  value: "{{workflow.parameters.subpath}}"
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: application-name
                  value: "{{workflow.parameters.application-name}}"
                - name: version
                  value: "{{tasks.generate-tag.outputs.parameters.version}}"
    - name: generate-tag
      outputs:
        parameters:
          - name: version
            valueFrom: 
              path: /tmp/version.txt
        volumeMounts:
          - name: workdir
            mountPath: /src
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args: 
          - |
            git rev-parse --short=7 HEAD > /tmp/git.txt
            date -u +"%Y%m%d-%H%M%S" > /tmp/date.txt
            echo "$(cat /tmp/date.txt)-$(cat /tmp/git.txt)" > /tmp/version.txt
              
              