

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mwstack-pipeline
spec:
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 1m
  entrypoint: build-and-deploy
  serviceAccountName: argo-workflow-svc
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  arguments:
    parameters:
      - name: giturl
        value: git@github.com:MatiWall/ 
      - name: repo
        value: FitTracker
      - name: registry
        value: docker-registry.mw.local/ #docker-registry-service.docker-registry.svc.cluster.local:5000
  templates:
    - name: build-and-deploy
      dag:
        tasks:
          - name: git-clone
            templateRef:
              name: git-template
              template: git-clone
            arguments:
              parameters:
                - name: url
                  value:  "{{workflow.parameters.giturl}}{{workflow.parameters.repo}}"
          - name: parse-pipeline
            template: parse-pipeline
            dependencies: [git-clone]
          - name: generate-tag
            dependencies: [git-clone]
            template: generate-tag
            arguments:
              parameters:
                - name: git-hash
                  value: "{{tasks.git-clone.outputs.parameters.git-hash}}"

          - name: build-push
            templateRef:
              name: docker-templates
              template: build-tag-push
            dependencies: [generate-tag, parse-pipeline]
            arguments:
              parameters:
                - name: application-name
                  value: "{{item.builds.name}}"
                - name: subpath
                  value: "{{item.builds.path}}"
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: version
                  value: "{{tasks.generate-tag.outputs.parameters.version}}"
            withParam: "{{tasks.parse-pipeline.outputs.result}}" # Loop over builds defined in the pipeline YAML
                
    - name: generate-tag
      inputs:
        parameters:
          - name: git-hash
      outputs:
        parameters:
          - name: version
            valueFrom: 
              path: /tmp/version.txt
        workingDir: /src
        volumeMounts:
          - name: workdir
            mountPath: /src
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args: 
          - |
            date -u +"%Y%m%d-%H%M%S" > /tmp/date.txt
            echo "$(cat /tmp/date.txt)-{{inputs.parameters.git-hash}}" > /tmp/version.txt

    - name: parse-pipeline
      script:
        image: python:3.10
        command: [python]
        source: |
          import subprocess
          import sys
          import json

          # install dependency
          subprocess.check_call([sys.executable, "-m", "pip", "-q", "install", "pyyaml"])

          import yaml

          with open("/src/mwstack-pipeline.yaml", "r") as f:
              pipeline = yaml.safe_load(f)

          json.dump(pipeline, sys.stdout)

        volumeMounts:
          - name: workdir
            mountPath: src/
  
              
              