apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-push-template
spec:
  entrypoint: git-push-entrypoint
  arguments:
    parameters:
      - name: username
      - name: email
      - name: commit-message
        value: 'Default commit message'
      - name: path

  templates:
    - name: git-push-entrypoint
      steps:
        - - name: git-push
            template: git-push
            arguments:
              parameters:
                - name: username
                  value: "{{workflow.parameters.username}}"
                - name: email
                  value: "{{workflow.parameters.email}}"
                - name: commit-message
                  value: "{{workflow.parameters.commit-message}}"

    - name: git-push
      inputs:
        parameters:
          - name: username
          - name: email
          - name: commit-message
          - name: path
      container:
        image: "alpine/git:latest"
        command: [sh, -c]
        args: |
            git config --global user.email "{{inputs.parameters.email}}"
            git config --global user.name "{{inputs.parameters.username}}"
            git add .
            git commit -m "{{workflow.parameters.commit-message}}"
            git push origin HEAD
        workingDir: /src/{{inputs.parameters.path}}
        volumeMounts:
          - name: workdir
            mountPath: /src
