apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-template
spec:
  entrypoint: git-push-entrypoint
  arguments:
    parameters:
      - name: username
      - name: email
      - name: commit-message
        value: 'Default commit message'
      - name: path

  templates:
    - name: git-push-entrypoint
      steps:
        - - name: git-push
            template: git-push
            arguments:
              parameters:
                - name: username
                  value: "{{workflow.parameters.username}}"
                - name: email
                  value: "{{workflow.parameters.email}}"
                - name: commit-message
                  value: "{{workflow.parameters.commit-message}}"

    - name: git-push
      inputs:
        parameters:
          - name: username
          - name: email
          - name: commit-message
          - name: path
      volumes:
        - name: ssh-key
          secret:
            secretName: matiwall-git-ssh
      container:
        image: "alpine/git:latest"
        command: [sh, -c]
        args: 
          - |
            mkdir -p ~/.ssh
            cp /mnt/ssh-key/ssh-privatekey ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            git config --global user.email "{{inputs.parameters.email}}"
            git config --global user.name "{{inputs.parameters.username}}"
            git remote -v
            git add .
            git commit -m "{{inputs.parameters.commit-message}}"
            git push origin HEAD
        workingDir: /src/{{inputs.parameters.path}}
        volumeMounts:
          - name: workdir
            mountPath: /src
          - name: ssh-key
            mountPath: /mnt/ssh-key


    - name: git-clone
      inputs:
        parameters:
          - name: url
      volumes:
        - name: ssh-key
          secret:
            secretName: matiwall-git-ssh
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            mkdir -p ~/.ssh
            cp /mnt/ssh-key/ssh-privatekey ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

            git clone "{{inputs.parameters.url}}"
        workingDir: /src
        volumeMounts:
          - name: workdir
            mountPath: /src
          - name: ssh-key
            mountPath: /mnt/ssh-key


