apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-templates
spec:
  serviceAccountName: argo-workflow-svc

  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  templates:
  - name: build-tag-push
    inputs:
      parameters:
        - name: subpath
        - name: registry
        - name: application-name
        - name: version

    volumes:
      - name: ca-bundle
        configMap:
          name: homelab-root-ca-bundle

    container:
      image: moby/buildkit:master
      command: [sh, -c]
      args:
        - |
          set -e

          IMAGE="{{inputs.parameters.registry}}{{inputs.parameters.application-name}}:{{inputs.parameters.version}}"

          buildctl-daemonless.sh build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=${IMAGE},push=true

      workingDir: /src/{{inputs.parameters.subpath}}
      env:
        - name: SSL_CERT_FILE
          value: /certs/ca.crt
        - name: REQUESTS_CA_BUNDLE
          value: /certs/ca.crt
      volumeMounts:
        - name: workdir
          mountPath: /src

        - name: ca-bundle
          mountPath: /certs/ca.crt
          subPath: root-certs.pem
          readOnly: true