apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-toml-config
data:
  buildkitd.toml: |
    debug = true

    [registry."your-registry.homelab"]
      ca = ["/home/user/certs/homelab-root-ca-bundle.pem"]