apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-toml-config
data:
  buildkitd.toml: |
    [registry."docker-registry.mw.local"]
      ca = ["/etc/buildkit/certs/homelab-root-ca-bundle.pem"]
