apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # Default values that will apply to all Workflows from this controller, unless overridden on the Workflow-level
  workflowDefaults: |
    metadata:
      annotations:
        argo: workflows
    spec:
      ttlStrategy:
        secondsAfterSuccess: 5
      parallelism: 3
  telemetry: |
    # Configure OpenTelemetry gRPC endpoint
    collector:
      address: "http://otelcollector-service.monitoring.svc.cluster.local:4317"
      insecure: true
  tracing: |
    # Enable distributed tracing (beta)
    enabled: true
    # Specify base URL of your tracing frontend to link from the Argo UI
    frontendUrl: "https://argo-workflow.mw.local/{{ .TraceID }}"
