---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-ssh-key
  namespace: argo
spec:
  encryptedData:
    ssh-privatekey: AgBUlYKb9thbMc6Aot3WtjUN0jtrsaThwB1qsnsquJiU2oTIoeRxsG/0J8Z7PwN8whCp0L6Wp490eNoZSyQxU3azdgskIr4MbmEK/+GZ7doSRQiHoAxb246U4D4gLGffBCJU8qGYnzonvxG/R1FySNIIVgTxQCAkouRY3ztDdShxIw0rIngOK+xsSHaM5ggoctq9HF74m41hCFgA1ObdC517Uhd4H0fxMcx5Y5VuBuiv1wzw36scR5bun5CocGoBQH7Q8iJR/5mNlDlEcKWNfUANVEvt70k36jJQeyGZg5Coyu2WvLzly7TW+RoPQBtyqCn52gBCZ2RjHhWMvhzvgYAg+cYx+UXMqY/uvH8Xz7Jv8fsVhg4FstRVZFzrVHsybbFSa5vZ6F4N3G16AWdXFPMKeP91HvsIy+SdBB9PwSYjUbN51XyuVoMHAaIvN1Jwhs/A7Fn1KUqz2o8ZxZTYHjcAaf/t9oLvD8gl8m8lqIUTSP19DAr2fOJopudpiRo1qM7PgyM+Xy32UIuvWaDrfovaMDxjRxWJoJ+H/p0BOesOJNg5LLck2y2zQ8oVT8Okychx+2PjCzdL5dPBeG8g18Ntfg1eRu3vwzFvgQN9x+E0X1pmQRAM51YHbuHIk/P0K4i29sv4TR450/DsTclfsHnc/Sf0CYAFLPCYnRVhS/ytOLWzpyR/fcJX0ui13ljbWM3Or5ZT0reTLcElkwVn3/6esmi0BNwnFU0WpfytBj+s4Me5ZxKk1vo7T9VHCVuuwxn3KaNiDlpivpOZM2SSfGsy7D8RTLvKPuvqfoIi63XvzbAKbyuJXNxGrJcxq0GXbMBc6pOrvW/wZ9fP2wVO1TJhBb5JBJ7fXZ9OhFXHKvFPx/+5rTyEOxeYPkdD7lyL4Z+lpJGBYmGudLNP2FH/5sZHiyQaTEMeYmKL8w0p3aUbN0j/XdI46MsDOKJt6H3ZOKr0rfhtvkvERFk9alwU+bFWNy/7RIAuFs5NMLzccDau1ClvsFwUdih8Kv7hHVRq2RYj25QWRXsUexBStSNQyWtNrXqBtcgpB9oQCHrCvw8WXTc6siWeYc6iCMy2bz9DtqA1ZQwtpiozuYrbaqY8fzZ2C5oKgnhsiVFUfVnqhHogvGaEyE60ae5HZseHvQ5Eu8GZGmOGf80iOJ+BDOORpCs4CMZuReW7Ljb9IjnwPjVHrmxkRkI3e39I4LICq32TXoVMrf0=
  template:
    metadata:
      name: argo-ssh-key
      namespace: argo
    type: kubernetes.io/ssh-auth
