apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-workflow-cert
  namespace: argo
spec:
  secretName: argocd-workflow-tls-secret
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - argo-workflow.mw.local
  duration: 8760h
  renewBefore: 720h
