apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-root-ca-bundle
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  # NB: Unless you pin the package providing these CAs, the default can change!
#  - useDefaultCAs: true

  # A Secret in the "trust" namespace; see "Trust Namespace" below for further details
#  - secret:
#      name: "my-db-tls"
#      key: "ca.crt"

  # Another Secret source, but this time using a label selector instead of a named Secret
#  - secret:
#      selector:
#        matchLabels:
#          fruit: apple
#      key: "ca.crt"

    - secret:
        name: local-root-ca-secret
        key: tls.crt
        namespace: cert-manager
  
  target:
    # Sync the bundle to a ConfigMap called `my-org.com` in every namespace which
    # has the label "linkerd.io/inject=enabled"
    # All ConfigMaps will include a PEM-formatted bundle, here named "root-certs.pem"
    # and in this case we also request binary formatted bundles in JKS and PKCS#12 formats,
    # here named "bundle.jks" and "bundle.p12".
    configMap:
      key: "root-certs.pem"
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
        labels:
          app.kubernetes.io/component: "trust-bundle"
    namespaceSelector:
      matchLabels:
        trust-manager/inject: "true"