apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Local Development CA
  secretName: local-root-ca-secret
  duration: 87600h   # 10 years
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: local-selfsigned
    kind: Issuer
